title: Help Center
description: Knowledge base for itemeter app users
theme: just-the-docs

logo: "/assets/images/logo.png"

url: https://help.itemeter.com

aux_links:
  Home page: https://itemeter.com
